version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

traefik:
  image: traefik:v2.10
  container_name: traefik
  restart: always
  command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.traefik.address=:80"  # Alterado para usar a porta 80
  ports:
    - "80:80"    # Expor o Traefik e seu painel de controle na porta 80
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"  # Permite que o Traefik se comunique com o Docker

  questions-api:
    image: node:14  # Substitua pela sua imagem Node.js ou crie a partir do Dockerfile
    container_name: questions-api
    build:
      context: .  # Certifique-se de que a API está no diretório correto
    ports:
      - "3000:3000"  # Porta onde a API escuta
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.questions-api.rule=Host(`questions-api-production.up.railway.app`)"
      - "traefik.http.services.questions-api.loadbalancer.server.port=3000"

volumes:
  mongo-data:

